import { Program, Level, Subject, Student, SchoolYear, User, SecurityCodes } from '../types';

export const INITIAL_SCHOOL_YEAR: SchoolYear = {
  id: 'sy-2026-2027',
  name: '2026-2027',
  startDate: '2026-09-01',
  endDate: '2027-07-31',
  isActive: true,
};

export const DEFAULT_SECURITY_CODES: SecurityCodes = {
  surveillantCode: 'ISGG-SURV-2026',
  directorCode: 'ISGG-DIR-9482',
  updatedAt: new Date().toISOString(),
};

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-surveillant-1',
    name: 'M. Diallo',
    email: 'm.diallo@isgg-edu.com',
    role: 'SURVEILLANT',
    title: 'Surveillant général',
    password: 'password123',
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    lastLogin: 'Aujourd\'hui à 07:45',
  },
  {
    id: 'usr-admin-1',
    name: 'Dr. K. Mensah',
    email: 'direction@isgg-edu.com',
    role: 'ADMIN',
    title: 'Directeur des études & Administrateur',
    password: 'password123',
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    lastLogin: 'Aujourd\'hui à 08:10',
  },
];

export const INITIAL_PROGRAMS: Program[] = [
  {
    id: 'prog-gi',
    name: 'Génie Informatique',
    code: 'GI',
    description: 'Systèmes d\'information, réseaux, bases de données et développement logiciel.',
    availableGroups: ['A', 'B'],
    isActive: true,
  },
  {
    id: 'prog-gc',
    name: 'Génie Civil / BTP',
    code: 'GC',
    description: 'Calcul des structures, béton armé, mécanique des sols et conduite de travaux.',
    availableGroups: ['A', 'B'],
    isActive: true,
  },
  {
    id: 'prog-gt',
    name: 'Géomètre Topographe',
    code: 'GT',
    description: 'Topométrie, géodésie, cartographie numérique et foncier.',
    availableGroups: ['A'],
    isActive: true,
  },
  {
    id: 'prog-gp',
    name: 'Gestion des Projets',
    code: 'GP',
    description: 'Planification, budgétisation, pilotage des opérations et gouvernance.',
    availableGroups: ['A', 'B'],
    isActive: true,
  },
  {
    id: 'prog-pgmp',
    name: 'Passation et Gestion des Marchés Publics',
    code: 'PGMP',
    description: 'Réglementation, passation, audits et exécution contractuelle des marchés.',
    availableGroups: ['A'],
    isActive: true,
  },
];

export const INITIAL_LEVELS: Level[] = [
  { id: 'lvl-l1', name: 'Licence 1', code: 'L1', order: 1 },
  { id: 'lvl-l2', name: 'Licence 2', code: 'L2', order: 2 },
  { id: 'lvl-l3', name: 'Licence 3', code: 'L3', order: 3 },
  { id: 'lvl-m1', name: 'Master 1', code: 'M1', order: 4 },
  { id: 'lvl-m2', name: 'Master 2', code: 'M2', order: 5 },
];

export const INITIAL_SUBJECTS: Subject[] = [
  // Génie Informatique - Licence 2 (Programme académique officiel - 21 Matières)
  { id: 'sub-l2-probabilites', name: 'Probabilités', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Dr. Tossou' },
  { id: 'sub-l2-algebre-lineaire', name: 'Algèbre linéaire', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Pr. Hounnou' },
  { id: 'sub-l2-tele-informatique-reseau', name: 'Télé Informatique et Réseau', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Ing. Dossou' },
  { id: 'sub-l2-maintenance-informatique', name: 'Maintenance informatique', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Ing. Houessou' },
  { id: 'sub-l2-poo-cpp', name: 'POO (C++)', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'M. Sossou' },
  { id: 'sub-l2-visual-basic', name: 'Visual Basic', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'M. Sossou' },
  { id: 'sub-l2-recherche-operationnelle', name: 'Recherche Opérationnelle', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Dr. Mensah' },
  { id: 'sub-l2-algorithmes-avances', name: 'Algorithmes avancés', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'M. Sossou' },
  { id: 'sub-l2-theorie-des-graphes', name: 'Théorie des graphes (Programmation)', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Pr. Hounnou' },
  { id: 'sub-l2-communication-ecrite-2', name: 'Communication Écrite et Orale 2 (CEO II)', code: 'CEO II', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Mme. Houinato' },
  { id: 'sub-l2-anglais-2', name: 'Anglais II', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'M. Johnson' },
  { id: 'sub-l2-deuxieme-langue-chinois', name: 'Deuxième langue vivante niveau 1 (Chinois)', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Mme. Wang' },
  { id: 'sub-l2-negociation-informatique', name: 'Négociation informatique', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Me. Soglo' },
  { id: 'sub-l2-applications-bureautique', name: 'Applications bureautique et de gestion', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Mme. Lawson' },
  { id: 'sub-l2-merise-2', name: 'Merise 2', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'M. Amoussou' },
  { id: 'sub-l2-atelier-genie-logiciel', name: 'Atelier Génie Logiciel', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l2-bases-de-donnees-2', name: 'Bases de données 2', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l2-acces-sgbd', name: 'Accès SGBD', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l2-projet-informatique-thematique', name: 'Projet informatique et thématique', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l2-programmation-web-2', name: 'Programmation Web 2', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'M. Amoussou' },
  { id: 'sub-l2-teleinformatique-reseau-2', name: 'Téléinformatique et réseau 2', code: '', programId: 'prog-gi', levelId: 'lvl-l2', teacherName: 'Ing. Dossou' },
  
  // Génie Informatique - Licence 1 (Programme académique officiel - 20 Matières)
  { id: 'sub-l1-analyse', name: 'Analyse', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Pr. Hounnou' },
  { id: 'sub-l1-statistique', name: 'Statistique', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Dr. Tossou' },
  { id: 'sub-l1-logique-combinatoire', name: 'Logique Combinatoire', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Ing. Dossou' },
  { id: 'sub-l1-mesures-electriques', name: 'Mesures électriques', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Ing. Houessou' },
  { id: 'sub-l1-architecture-technologies', name: 'Architecture et technologies des ordinateurs', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l1-droit-civil', name: 'Droit civil', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Me. Soglo' },
  { id: 'sub-l1-droit-commercial', name: 'Droit commercial', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Me. Soglo' },
  { id: 'sub-l1-informatique-fondamentale', name: 'Informatique Fondamentale', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'M. Sossou' },
  { id: 'sub-l1-algorithme', name: 'Algorithme', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'M. Sossou' },
  { id: 'sub-l1-economie-generale', name: 'Economie générale', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Dr. Mensah' },
  { id: 'sub-l1-economie-entreprise', name: 'Economie d\'entreprise', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Mme. Lawson' },
  { id: 'sub-l1-comptabilite-societes', name: 'Comptabilité des Sociétés', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Mme. Lawson' },
  { id: 'sub-l1-comptabilite-generale', name: 'Comptabilité Générale', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Mme. Lawson' },
  { id: 'sub-l1-base-de-donnees', name: 'Base de données', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l1-merise-1', name: 'Merise l', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'M. Amoussou' },
  { id: 'sub-l1-langage-c', name: 'Langage C', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'M. Sossou' },
  { id: 'sub-l1-programmation-web-1', name: 'Programmation web 1', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'M. Amoussou' },
  { id: 'sub-l1-projet-informatique', name: 'Projet informatique', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l1-anglais-1', name: 'Anglais niveau 1', code: '', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'M. Johnson' },
  { id: 'sub-l1-communication-1', name: 'Communication Ecrite et Orale 1', code: 'CEO 1', programId: 'prog-gi', levelId: 'lvl-l1', teacherName: 'Mme. Houinato' },
  
  // Génie Informatique - Licence 3 (Programme académique officiel - 17 Matières)
  { id: 'sub-l3-entreprenariat', name: 'Entreprenariat', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Dr. Mensah' },
  { id: 'sub-l3-droit', name: 'Droit', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Me. Soglo' },
  { id: 'sub-l3-education-financiere', name: 'Education financière et auto-emploi', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Mme. Lawson' },
  { id: 'sub-l3-teleinformatique-reseaux-3', name: 'Téléinformatique et Réseaux 3', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Ing. Dossou' },
  { id: 'sub-l3-architecture-systemes-exploitation', name: 'Architecture des systèmes d\'exploitation', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l3-base-de-donnees-avancees', name: 'Base de données avancées', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l3-oracle', name: 'Oracle', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l3-methodologie-redaction-memoire', name: 'Méthodologie de Rédaction de Mémoire', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Pr. Hounnou' },
  { id: 'sub-l3-teeo-3', name: 'TEEO 3', code: 'TEEO 3', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Mme. Houinato' },
  { id: 'sub-l3-anglais-du-travail-3', name: 'Anglais du travail 3', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'M. Johnson' },
  { id: 'sub-l3-java', name: 'Java', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'M. Sossou' },
  { id: 'sub-l3-langage-cpp', name: 'Langage C ++', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'M. Sossou' },
  { id: 'sub-l3-programmation-web-3', name: 'Programmation web 3', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'M. Amoussou' },
  { id: 'sub-l3-programmation-android', name: 'Programmation Android', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'M. Amoussou' },
  { id: 'sub-l3-atelier-genie-logiciel-2', name: 'Atelier Génie Logiciel 2', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Dr. Agbossou' },
  { id: 'sub-l3-uml', name: 'UML', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'M. Amoussou' },
  { id: 'sub-l3-stage-soutenance-memoire', name: 'Stage et soutenance de mémoire', code: '', programId: 'prog-gi', levelId: 'lvl-l3', teacherName: 'Pr. Hounnou' },

  // Génie Civil / BTP - Licence 3
  { id: 'sub-gc-l3-ba', name: 'Béton Armé', code: 'BA301', programId: 'prog-gc', levelId: 'lvl-l3', teacherName: 'Ing. Kpadonou' },
  { id: 'sub-gc-l3-ms', name: 'Mécanique des sols', code: 'MS302', programId: 'prog-gc', levelId: 'lvl-l3', teacherName: 'Dr. Tchabi' },
  { id: 'sub-gc-l3-rdm', name: 'Résistance des matériaux (RDM)', code: 'RDM303', programId: 'prog-gc', levelId: 'lvl-l3', teacherName: 'Ing. Kpadonou' },

  // Génie Civil / BTP - Licence 2
  { id: 'sub-gc-l2-ms', name: 'Mécanique des sols', code: 'MS201', programId: 'prog-gc', levelId: 'lvl-l2', teacherName: 'Dr. Tchabi' },
  { id: 'sub-gc-l2-rdm', name: 'Résistance des matériaux', code: 'RDM202', programId: 'prog-gc', levelId: 'lvl-l2', teacherName: 'Ing. Kpadonou' },

  // Génie Civil / BTP - Licence 1
  { id: 'sub-gc-l1-dt', name: 'Dessin technique & Bâtiment', code: 'DT101', programId: 'prog-gc', levelId: 'lvl-l1', teacherName: 'M. Zannou' },

  // Géomètre Topographe - Licence 1
  { id: 'sub-gt-l1-dt', name: 'Dessin technique', code: 'DT102', programId: 'prog-gt', levelId: 'lvl-l1', teacherName: 'M. Zannou' },
  { id: 'sub-gt-l1-topo', name: 'Topométrie générale', code: 'TOPO101', programId: 'prog-gt', levelId: 'lvl-l1', teacherName: 'Ing. Houessou' },

  // Gestion des Projets - Licence 2
  { id: 'sub-gp-l2-compta', name: 'Comptabilité analytique', code: 'COMP201', programId: 'prog-gp', levelId: 'lvl-l2', teacherName: 'Mme. Lawson' },
  { id: 'sub-gp-l2-gp', name: 'Management de projet', code: 'MGT202', programId: 'prog-gp', levelId: 'lvl-l2', teacherName: 'Dr. Mensah' },

  // Gestion des Projets - Licence 3
  { id: 'sub-gp-l3-mkt', name: 'Marketing & Stratégie', code: 'MKT301', programId: 'prog-gp', levelId: 'lvl-l3', teacherName: 'Mme. Lawson' },
  { id: 'sub-gp-l3-audit', name: 'Audit et contrôle de gestion', code: 'AUD302', programId: 'prog-gp', levelId: 'lvl-l3', teacherName: 'Dr. Mensah' },

  // Passation et Gestion des Marchés Publics
  { id: 'sub-pgmp-l2-droit', name: 'Droit des marchés publics', code: 'DMP201', programId: 'prog-pgmp', levelId: 'lvl-l2', teacherName: 'Me. Soglo' },
  { id: 'sub-pgmp-l3-proc', name: 'Procédures de passation', code: 'PPP301', programId: 'prog-pgmp', levelId: 'lvl-l3', teacherName: 'Me. Soglo' },
];

export const INITIAL_STUDENTS: Student[] = [
  // Primary scenario student: APITHY Mathieu (Génie Informatique, Licence 2, Classe A, 7 initial absences)
  {
    id: 'stu-apithy-mathieu',
    matricule: 'ISGG-2024-042',
    firstName: 'Mathieu',
    lastName: 'APITHY',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'mathieu.apithy@etud.isgg-edu.com',
    phone: '+229 97 12 34 56',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  // KOFFI for step 15-17 of scenario:
  {
    id: 'stu-koffi-kouame',
    matricule: 'ISGG-2024-043',
    firstName: 'Kouamé',
    lastName: 'KOFFI',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'kouame.koffi@etud.isgg-edu.com',
    phone: '+229 96 23 45 67',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  // ADJOVI for step 29 class list:
  {
    id: 'stu-adjovi-marc',
    matricule: 'ISGG-2024-044',
    firstName: 'Marc',
    lastName: 'ADJOVI',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'B',
    email: 'marc.adjovi@etud.isgg-edu.com',
    phone: '+229 95 34 56 78',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-agboton-serge',
    matricule: 'ISGG-2024-045',
    firstName: 'Serge',
    lastName: 'AGBOTON',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'B',
    email: 'serge.agboton@etud.isgg-edu.com',
    phone: '+229 97 45 67 89',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-assi-clarisse',
    matricule: 'ISGG-2024-046',
    firstName: 'Clarisse',
    lastName: 'ASSI',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'clarisse.assi@etud.isgg-edu.com',
    phone: '+229 94 56 78 90',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },

  // Official ISGG Students from Daily Report Template (09/09/2026):
  {
    id: 'stu-aboki-job',
    matricule: 'ISGG-2024-051',
    firstName: 'Job',
    lastName: 'ABOKI',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'job.aboki@etud.isgg-edu.com',
    phone: '+229 97 10 20 30',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-amossou-marcelin',
    matricule: 'ISGG-2024-052',
    firstName: 'Marcelin',
    lastName: 'AMOSSOU',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'marcelin.amossou@etud.isgg-edu.com',
    phone: '+229 97 11 22 33',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-atioukpe-carlos',
    matricule: 'ISGG-2024-053',
    firstName: 'Carlos',
    lastName: 'ATIOUKPE',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'carlos.atioukpe@etud.isgg-edu.com',
    phone: '+229 97 12 23 34',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-bouraima-abdel',
    matricule: 'ISGG-2024-054',
    firstName: 'Abdel',
    lastName: 'BOURAIMA',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'abdel.bouraima@etud.isgg-edu.com',
    phone: '+229 97 13 24 35',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-chabi-isdeen',
    matricule: 'ISGG-2024-055',
    firstName: 'Isdeen',
    lastName: 'CHABI',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'isdeen.chabi@etud.isgg-edu.com',
    phone: '+229 97 14 25 36',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-doumatey-chimene',
    matricule: 'ISGG-2024-056',
    firstName: 'Chimène',
    lastName: 'DOUMATEY',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'chimene.doumatey@etud.isgg-edu.com',
    phone: '+229 97 15 26 37',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-ganni-loukman',
    matricule: 'ISGG-2024-057',
    firstName: 'Loukman',
    lastName: 'GANNI',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'loukman.ganni@etud.isgg-edu.com',
    phone: '+229 97 16 27 38',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-nata-jean-yves',
    matricule: 'ISGG-2024-058',
    firstName: 'Jean-Yves',
    lastName: 'NATA',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'jean-yves.nata@etud.isgg-edu.com',
    phone: '+229 97 17 28 39',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-acakpo-andre',
    matricule: 'ISGG-2024-059',
    firstName: 'André',
    lastName: 'ACAKPO',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'B',
    email: 'andre.acakpo@etud.isgg-edu.com',
    phone: '+229 97 18 29 40',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-bode-stephane',
    matricule: 'ISGG-2024-060',
    firstName: 'Stéphane',
    lastName: 'BODE',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'B',
    email: 'stephane.bode@etud.isgg-edu.com',
    phone: '+229 97 19 30 41',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-gnanguenon-gloria',
    matricule: 'ISGG-2024-061',
    firstName: 'Gloria',
    lastName: 'GNANGUENON',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'B',
    email: 'gloria.gnanguenon@etud.isgg-edu.com',
    phone: '+229 97 20 31 42',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-oladeyo-koudjibou',
    matricule: 'ISGG-2024-062',
    firstName: 'Koudjibou',
    lastName: 'OLADEYO',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'B',
    email: 'koudjibou.oladeyo@etud.isgg-edu.com',
    phone: '+229 97 21 32 43',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-sero-tikande',
    matricule: 'ISGG-2024-063',
    firstName: 'Tikandé',
    lastName: 'SERO',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'B',
    email: 'tikande.sero@etud.isgg-edu.com',
    phone: '+229 97 22 33 44',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-sidi-delphin',
    matricule: 'ISGG-2024-064',
    firstName: 'Delphin',
    lastName: 'SIDI',
    programId: 'prog-gi',
    levelId: 'lvl-l2',
    classGroup: 'B',
    email: 'delphin.sidi@etud.isgg-edu.com',
    phone: '+229 97 23 34 45',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },

  // Mockup history students:
  {
    id: 'stu-kouassi-yao',
    matricule: 'ISGG-2023-018',
    firstName: 'Yao',
    lastName: 'KOUASSI',
    programId: 'prog-gc',
    levelId: 'lvl-l3',
    classGroup: 'A',
    email: 'yao.kouassi@etud.isgg-edu.com',
    phone: '+229 97 11 22 33',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2023-09-18T08:00:00Z',
  },
  {
    id: 'stu-traore-aminata',
    matricule: 'ISGG-2024-089',
    firstName: 'Aminata',
    lastName: 'TRAORÉ',
    programId: 'prog-gp',
    levelId: 'lvl-l2',
    classGroup: 'B',
    email: 'aminata.traore@etud.isgg-edu.com',
    phone: '+229 96 22 33 44',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-diop-mamadou',
    matricule: 'ISGG-2025-003',
    firstName: 'Mamadou',
    lastName: 'DIOP',
    programId: 'prog-gi',
    levelId: 'lvl-l1',
    classGroup: 'A',
    email: 'mamadou.diop@etud.isgg-edu.com',
    phone: '+229 95 33 44 55',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2025-09-15T08:00:00Z',
  },
  {
    id: 'stu-houngbedji-chantal',
    matricule: 'ISGG-2025-014',
    firstName: 'Chantal',
    lastName: 'HOUNGBEDJI',
    programId: 'prog-gi',
    levelId: 'lvl-l1',
    classGroup: 'A',
    email: 'chantal.houngbedji@etud.isgg-edu.com',
    phone: '+229 97 78 89 90',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2025-09-15T08:00:00Z',
  },
  {
    id: 'stu-dossou-kevin',
    matricule: 'ISGG-2025-028',
    firstName: 'Kévin',
    lastName: 'DOSSOU',
    programId: 'prog-gi',
    levelId: 'lvl-l1',
    classGroup: 'B',
    email: 'kevin.dossou@etud.isgg-edu.com',
    phone: '+229 96 89 90 01',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2025-09-15T08:00:00Z',
  },
  {
    id: 'stu-bamba-fatou',
    matricule: 'ISGG-2024-061',
    firstName: 'Fatou',
    lastName: 'BAMBA',
    programId: 'prog-gc',
    levelId: 'lvl-l2',
    classGroup: 'B',
    email: 'fatou.bamba@etud.isgg-edu.com',
    phone: '+229 94 44 55 66',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-kone-ibrahim',
    matricule: 'ISGG-2023-094',
    firstName: 'Ibrahim',
    lastName: 'KONÉ',
    programId: 'prog-gp',
    levelId: 'lvl-l3',
    classGroup: 'A',
    email: 'ibrahim.kone@etud.isgg-edu.com',
    phone: '+229 97 55 66 77',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2023-09-18T08:00:00Z',
  },
  {
    id: 'stu-coulibaly-mariam',
    matricule: 'ISGG-2025-055',
    firstName: 'Mariam',
    lastName: 'COULIBALY',
    programId: 'prog-gt',
    levelId: 'lvl-l1',
    classGroup: 'A',
    email: 'mariam.coulibaly@etud.isgg-edu.com',
    phone: '+229 96 66 77 88',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2025-09-15T08:00:00Z',
  },
  {
    id: 'stu-sow-amadou',
    matricule: 'ISGG-2024-102',
    firstName: 'Amadou',
    lastName: 'SOW',
    programId: 'prog-gc',
    levelId: 'lvl-l3',
    classGroup: 'A',
    email: 'amadou.sow@etud.isgg-edu.com',
    phone: '+229 95 77 88 99',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
  {
    id: 'stu-toure-aissatou',
    matricule: 'ISGG-2024-115',
    firstName: 'Aïssatou',
    lastName: 'TOURÉ',
    programId: 'prog-pgmp',
    levelId: 'lvl-l2',
    classGroup: 'A',
    email: 'aissatou.toure@etud.isgg-edu.com',
    phone: '+229 94 88 99 00',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isActive: true,
    createdAt: '2024-09-20T08:00:00Z',
  },
];
